### ISSUE TITLE
Loading value

### ISSUE THREAD

**Issue by joeljeske** [bsonntag/react-use-promise#2]
Great work, I’m excited to see more micro hooks like this :)

It would likely be nice to have a loading flag indicating if the promise is resolved yet or not.

I would think that every first render would not be ready since promises resolve on next tick even if they are settled.

**Comment by bsonntag** [comment]
I thought about this initially, but then figured that this can be done (outside the hook) by checking if both `result` and `error` are `null`.

```js
const isResolving = !result && !error;
```

Now that I've giving it more thought, I see that this won't work when the promise actually resolves to `null` (or other falsey value for that matter), so it should actually be handled by `usePromise` internally.

Please submit a PR if you'd like to play around with it.

**Comment by benneq** [comment]
@bsonntag I guess, that's not working for all cases.
For example if you have a Promise that actually returns null or undefined on success. (the same for error). We have a lot of API calls like `deleteXYZ` that won't return anything.

Though there should be some more properties:
- `result` - the result data
- `error` - the error data
- `isLoading` - boolean. false before and after promise. true while promise is running 
- `isResult` - boolean. true when promise resolved
- `isError` - boolean. true when promise rejected
