### ISSUE TITLE
Accept undefined as given promise

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [bsonntag/react-use-promise#39]
I use this pattern a lot of times:

```ts
const [promise, setPromise] = useState<Promise<any | undefined>>(Promise.resolve(undefined))
const [result, error] = usePromise(promise, [promise])
```

Ideally, the `promise` would just be `Promise<any> | undefined`, but since `usePromise` needs a promise, I have to use `Promise<undefined>`, along with a `Promise.resolve(undefined)`. This is extra work and less performance.

My suggestion is to make this ok: `usePromise(undefined)`. Then it should return [undefined, undefined, 'pending']. Or maybe an new state for when `undefined` is given.

**Comment by bsonntag** [comment]
`usePromise(undefined)` should work, and it should indeed return `[undefined, undefined, 'pending']`. I don't have that exact case covered in the tests, but I have a similar one [here](https://github.com/bsonntag/react-use-promise/blob/aaaa4d9cf94bea823f1f30cb7fec535024d3bace/src/index.test.js#L87).

What is it returning for you?

**Comment by ChocolateLoverRaj** [comment]
> `usePromise(undefined)` should work

> What is it returning for you?

I never tried doing that because I got a TypeScript error. The types don't allow `undefined`.

**Comment by bsonntag** [comment]
Ah, so the types in `index.d.ts` are wrong. Would you be able to submit a PR with a fix?

**Comment by ChocolateLoverRaj** [comment]
@bsonntag Sure
