### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [bsonntag/react-use-promise#42]
I installed the dependencies with Pnpm, but I think there is still something missing because when I run the tests I get this error:

`Couldn't find preset "@babel/env" relative to directory "C:\\Users\\rajas\\Documents\\GitHub\\react-use-promise"`

**Comment by bsonntag** [comment]
Can you please check if [this branch](https://github.com/bsonntag/react-use-promise/pull/44) fixes your problem?

**Comment by ChocolateLoverRaj** [comment]
> Can you please check if [this branch](https://github.com/bsonntag/react-use-promise/pull/44) fixes your problem?

@bsonntag  Yes it does
